### ISSUE TITLE
crashes every time i start it up 

### ISSUE THREAD

**Issue by timohunker** [NillerMedDild/Enigmatica5#19]
**Modpack version**
0.2.0

**Issue**
when i press play it go's away for a sec and then its says game crashed 

**Logs**
[14:52:50] [main/INFO]: ModLauncher running: args [--username, Timohunker, --version, forge-30.0.41, --gameDir, C:\Program Files (x86)\Minecraft\Instances\Enigmatica 5, --assetsDir, C:\Program Files (x86)\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 133153b2aefb41588827464c5ef8c879, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 1680, --height, 1050, --launchTarget, fmlclient, --fml.forgeVersion, 30.0.41, --fml.mcVersion, 1.15.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20191217.105819]
[14:52:50] [main/INFO]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[14:52:50] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[14:52:50] [main/FATAL]: Failed to find Minecraft resource version 1.15.1-20191217.105819 at C:\Program Files (x86)\Minecraft\Install\libraries\net\minecraftforge\forge\1.15.1-30.0.41\forge-1.15.1-30.0.41-client.jar
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$136/40075281.accept(Unknown Source)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:195)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$84/1108924067.accept(Unknown Source)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[14:52:50] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by timohunker** [comment]
i don't know what to do anymore and srry for bad english ;)

**Comment by NielsPilgaard** [comment]
No worries - Try the GDLauncher instead of Twitch, it has issues with Minecraft versions past 1.13
